# Generated by Django 4.2.4 on 2023-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_projectlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlogs',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
